version: "3.7"

services: 
    # copied from https://hub.docker.com/_/mysql/?tab=description
    mysql:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            #MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - 3306:3306
        # note: uncomment volume ONLY if you want to keep databases and password settings
        #volumes:
        #    - dotmim-mysql-data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    mssql:
        # see: https://docs.docker.com/compose/aspnet-mssql-compose/
        image: "mcr.microsoft.com/mssql/server"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Secr3T!!!
        ports:
            - 1444:1433

#volumes:
#    dotmim-mysql-data:
    