using Wormhole.Sync.Batch;
using Wormhole.Sync.Enumerations;
using Wormhole.Sync.Web.Client.BackwardCompatibility;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Wormhole.Sync.Web.Client
{

    /// <summary>
    /// Represents the SyncContext for the current sync session in an HTTP message.
    /// </summary>
    public interface IScopeMessage
    {
        /// <summary>
        /// Gets or Sets the SyncContext.
        /// </summary>
        SyncContext SyncContext { get; set; }
    }

    /// <summary>
    /// HttpMessage containing a batch changes from the server.
    /// </summary>
    [DataContract(Name = "changesres"), Serializable]
    public class HttpMessageSendChangesResponse : IScopeMessage
    {

        /// <inheritdoc cref="HttpMessageSendChangesResponse"/>/>
        public HttpMessageSendChangesResponse() { }

        /// <inheritdoc cref="HttpMessageSendChangesResponse"/>/>
        public HttpMessageSendChangesResponse(SyncContext context)
            => this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <summary>
        /// Gets or Sets the Server HttpStep.
        /// </summary>
        [DataMember(Name = "ss", IsRequired = true, Order = 1)]
        public HttpStep ServerStep { get; set; }

        /// <summary>
        /// Gets or Sets the SyncContext.
        /// </summary>
        [DataMember(Name = "sc", IsRequired = true, Order = 2)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets the current batch index, send from the server.
        /// </summary>
        [DataMember(Name = "bi", IsRequired = true, Order = 3)]
        public int BatchIndex { get; set; }

        /// <summary>
        /// Gets or sets the number of batch to send.
        /// </summary>
        [DataMember(Name = "bc", IsRequired = false, Order = 4)]
        public int BatchCount { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether gets or Sets if this is the last Batch send from the server.
        /// </summary>
        [DataMember(Name = "islb", IsRequired = true, Order = 5)]
        public bool IsLastBatch { get; set; }

        /// <summary>
        /// Gets or sets the remote client timestamp generated by the server database.
        /// </summary>
        [DataMember(Name = "rct", IsRequired = true, Order = 6)]
        public long RemoteClientTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the BatchParInfo send from the server.
        /// </summary>
        [DataMember(Name = "changes", IsRequired = true, Order = 7)]
        public ContainerSet Changes { get; set; } // BE CAREFUL: If changes the order, change it too in "ContainerSetBoilerPlate" !

        /// <summary>
        /// Gets or sets the changes stats from the server.
        /// </summary>
        [DataMember(Name = "scs", IsRequired = true, Order = 8)]
        public DatabaseChangesSelected ServerChangesSelected { get; set; }

        /// <summary>
        /// Gets or sets the changes stats from the server.
        /// </summary>
        [DataMember(Name = "cca", IsRequired = true, Order = 9)]
        public DatabaseChangesApplied ClientChangesApplied { get; set; }

        /// <summary>
        /// Gets or Sets the conflict resolution policy from the server.
        /// </summary>
        [DataMember(Name = "policy", IsRequired = true, Order = 10)]
        public ConflictResolutionPolicy ConflictResolutionPolicy { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the session was ended with this response.
        /// </summary>
        [DataMember(Name = "sessionEnded", IsRequired = false, Order = 11)]
        public bool SessionEnded { get; set; }

        /// <summary>
        /// Gets or sets the server timestamp when session was ended.
        /// </summary>
        [DataMember(Name = "serverTimestamp", IsRequired = false, Order = 12)]
        public long? ServerTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets the server's unique scope identifier.
        /// </summary>
        [DataMember(Name = "ssid", IsRequired = false, EmitDefaultValue = false, Order = 13)]
        public Guid ServerScopeId { get; set; }
    }

    /// <summary>
    /// HttpMessage to get more changes from the server.
    /// </summary>
    [DataContract(Name = "morechangesreq"), Serializable]
    public class HttpMessageGetMoreChangesRequest : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageGetMoreChangesRequest"/>/>
        public HttpMessageGetMoreChangesRequest() { }

        /// <inheritdoc cref="HttpMessageGetMoreChangesRequest"/>/>
        public HttpMessageGetMoreChangesRequest(SyncContext context, int batchIndexRequested)
        {
            this.BatchIndexRequested = batchIndexRequested;
            this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets the batch index requested.
        /// </summary>
        [DataMember(Name = "bireq", IsRequired = true, Order = 2)]
        public int BatchIndexRequested { get; set; }
    }

    /// <summary>
    /// HttpMessage to get changes from the server.
    /// </summary>
    [DataContract(Name = "changesreq"), Serializable]
    public class HttpMessageSendChangesRequest : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageSendChangesRequest" />
        public HttpMessageSendChangesRequest()
        {
        }

        /// <inheritdoc cref="HttpMessageSendChangesRequest" />
        public HttpMessageSendChangesRequest(SyncContext context, ScopeInfoClient cScopeInfoClient)
        {
            this.SyncContext = context;
            this.ScopeInfoClient = cScopeInfoClient;
            this.IsLastBatch = true;
            this.BatchCount = 0;
            this.BatchIndex = 0;
            this.Changes = new ContainerSet();
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets the client scope info.
        /// </summary>
        [DataMember(Name = "scopeclient", IsRequired = false, Order = 2)]
        public ScopeInfoClient ScopeInfoClient { get; set; }

        /// <summary>
        /// Gets or sets get the current batch index.
        /// </summary>
        [DataMember(Name = "bi", IsRequired = true, Order = 3)]
        public int BatchIndex { get; set; }

        /// <summary>
        /// Gets or sets get the current batch count.
        /// </summary>
        [DataMember(Name = "bc", IsRequired = false, Order = 4)]
        public int BatchCount { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether gets or Sets if this is the last Batch to sent to server.
        /// </summary>
        [DataMember(Name = "islb", IsRequired = true, Order = 5)]
        public bool IsLastBatch { get; set; }

        /// <summary>
        /// Gets or sets changes to send.
        /// </summary>
        [DataMember(Name = "changes", IsRequired = true, Order = 6)]
        public ContainerSet Changes { get; set; }

        /// <summary>
        /// Gets or sets client last sync timestamp.
        /// </summary>
        [DataMember(Name = "clst", IsRequired = false, Order = 7)] // IsRequired = false to preserve backward compat
        public long ClientLastSyncTimestamp { get; set; }

        /// <summary>
        /// Gets or sets pre 0.9.6 old ScopeInfo object.
        /// </summary>
        [DataMember(Name = "scope", IsRequired = false, Order = 8)] // IsRequired = false to preserve backward compat
        public OldScopeInfo OldScopeInfo { get; set; }
    }

    /// <summary>
    /// HttpMessage containing a schema from the server.
    /// </summary>
    [DataContract(Name = "ensureschemares"), Serializable]
    public class HttpMessageEnsureSchemaResponse : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageEnsureSchemaResponse" />
        public HttpMessageEnsureSchemaResponse()
        {
        }

        /// <inheritdoc cref="HttpMessageEnsureSchemaResponse" />
        public HttpMessageEnsureSchemaResponse(SyncContext context, ScopeInfo sScopeInfo)
        {
            this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            this.ServerScopeInfo = sScopeInfo ?? throw new ArgumentNullException(nameof(sScopeInfo));
            this.Schema = sScopeInfo.Schema;
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the schema because the ServerScopeInfo won't have it since it's marked (on purpose) as IgnoreDataMember (and then not serialized).
        /// </summary>
        [DataMember(Name = "schema", IsRequired = true, Order = 2)]
        public SyncSet Schema { get; set; }

        /// <summary>
        /// Gets or Sets the server scope info, from server.
        /// </summary>
        [DataMember(Name = "ssi", IsRequired = true, Order = 3)]
        public ScopeInfo ServerScopeInfo { get; set; }
    }

    /// <summary>
    /// HttpMessage containing scopes from the server.
    /// </summary>
    [DataContract(Name = "ensurescopesres"), Serializable]
    public class HttpMessageEnsureScopesResponse : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageEnsureScopesResponse"/>
        public HttpMessageEnsureScopesResponse()
        {
        }

        /// <inheritdoc cref="HttpMessageEnsureScopesResponse"/>
        public HttpMessageEnsureScopesResponse(SyncContext context, ScopeInfo sScopeInfo)
        {
            this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            this.ServerScopeInfo = sScopeInfo ?? throw new ArgumentNullException(nameof(sScopeInfo));
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the schema option (without schema itself, that is not serializable).
        /// </summary>
        [DataMember(Name = "serverscope", IsRequired = true, Order = 2)]
        public ScopeInfo ServerScopeInfo { get; set; }
    }

    /// <summary>
    /// HttpMessage to get scopes from the server.
    /// </summary>
    [DataContract(Name = "ensurereq"), Serializable]
    public class HttpMessageEnsureScopesRequest : IScopeMessage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpMessageEnsureScopesRequest"/> class.
        /// Create a new message to web remote server.
        /// Scope info table name is not provided since we do not care about it on the server side.
        /// </summary>
        public HttpMessageEnsureScopesRequest() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="HttpMessageEnsureScopesRequest"/> class.
        /// Create a new message to web remote server.
        /// Scope info table name is not provided since we do not care about it on the server side.
        /// </summary>
        public HttpMessageEnsureScopesRequest(SyncContext context) => this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }
    }

    /// <summary>
    /// HttpMessage to get an hypothetical operation override from the server.
    /// </summary>
    [DataContract(Name = "opreq"), Serializable]
    public class HttpMessageOperationRequest : IScopeMessage
    {

        /// <inheritdoc cref="HttpMessageOperationRequest" />
        public HttpMessageOperationRequest() { }

        /// <inheritdoc cref="HttpMessageOperationRequest" />
        public HttpMessageOperationRequest(SyncContext context, ScopeInfo cScopeInfo, ScopeInfoClient cScopeInfoClient)
        {
            this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            this.ScopeInfoFromClient = cScopeInfo;
            this.ScopeInfoClient = cScopeInfoClient;
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the reference scope for local repository, stored on server.
        /// </summary>
        [DataMember(Name = "scope", IsRequired = true, Order = 2)]
        public ScopeInfo ScopeInfoFromClient { get; set; }

        /// <summary>
        /// Gets or Sets the reference scope for local repository, stored on server.
        /// </summary>
        [DataMember(Name = "scopeclient", IsRequired = true, Order = 3)]
        public ScopeInfoClient ScopeInfoClient { get; set; }
    }

    /// <summary>
    /// HttpMessage containing an hypothetical operation override from the server.
    /// </summary>
    [DataContract(Name = "opres"), Serializable]
    public class HttpMessageOperationResponse : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageOperationResponse" />
        public HttpMessageOperationResponse() { }

        /// <inheritdoc cref="HttpMessageOperationResponse" />
        public HttpMessageOperationResponse(SyncContext context, SyncOperation syncOperation)
        {
            this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            this.SyncOperation = syncOperation;
        }

        /// <inheritdoc  />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the Sync Operation sent from the server that should be run on the client.
        /// </summary>
        [DataMember(Name = "so", IsRequired = true, Order = 2)]
        public SyncOperation SyncOperation { get; set; }
    }

    /// <summary>
    /// HttpMessage to containing the remote timestamp from the server.
    /// </summary>
    [DataContract(Name = "remotetsres"), Serializable]
    public class HttpMessageRemoteTimestampResponse : IScopeMessage
    {

        /// <inheritdoc cref="HttpMessageRemoteTimestampResponse" />
        public HttpMessageRemoteTimestampResponse()
        {
        }

        /// <inheritdoc cref="HttpMessageRemoteTimestampResponse" />
        public HttpMessageRemoteTimestampResponse(SyncContext context, long remoteClientTimestamp)
        {
            this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            this.RemoteClientTimestamp = remoteClientTimestamp;
        }

        /// <inheritdoc  />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets the remote client timestamp generated by the server database.
        /// </summary>
        [DataMember(Name = "rct", IsRequired = true, Order = 2)]
        public long RemoteClientTimestamp { get; set; }
    }

    /// <summary>
    /// HttpMessage to get the remote timestamp from the server.
    /// </summary>
    [DataContract(Name = "remotetsreq"), Serializable]
    public class HttpMessageRemoteTimestampRequest : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageRemoteTimestampRequest" />
        public HttpMessageRemoteTimestampRequest() { }

        /// <inheritdoc cref="HttpMessageRemoteTimestampRequest" />
        public HttpMessageRemoteTimestampRequest(SyncContext context)
            => this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }
    }

    /// <summary>
    /// HttpMessage to get a summary to apply on the client, from the server.
    /// </summary>
    [DataContract(Name = "summary"), Serializable]
    public class HttpMessageSummaryResponse : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageSummaryResponse" />
        public HttpMessageSummaryResponse()
        {
        }

        /// <inheritdoc cref="HttpMessageSummaryResponse" />
        public HttpMessageSummaryResponse(SyncContext context)
            => this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <summary>
        /// Gets or Sets the SyncContext.
        /// </summary>
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the conflict resolution policy from the server.
        /// </summary>
        [DataMember(Name = "bi", IsRequired = false, EmitDefaultValue = false, Order = 2)]
        public BatchInfo BatchInfo { get; set; }

        /// <summary>
        /// Gets or sets the remote client timestamp generated by the server database.
        /// </summary>
        [DataMember(Name = "rct", IsRequired = false, Order = 3)]
        public long RemoteClientTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the HttpStep.
        /// </summary>
        [DataMember(Name = "step", IsRequired = true, Order = 4)]
        public HttpStep Step { get; set; }

        /// <summary>
        /// Gets or Sets the container changes when in memory requested by the client.
        /// </summary>
        [DataMember(Name = "changes", IsRequired = false, EmitDefaultValue = false, Order = 5)]
        public ContainerSet Changes { get; set; }

        /// <summary>
        /// Gets or Sets the summary server changes applied on server.
        /// </summary>
        [DataMember(Name = "scs", IsRequired = false, EmitDefaultValue = false, Order = 6)]
        public DatabaseChangesSelected ServerChangesSelected { get; set; }

        /// <summary>
        /// Gets or Sets the summary client changes applied on client.
        /// </summary>
        [DataMember(Name = "cca", IsRequired = false, EmitDefaultValue = false, Order = 7)]
        public DatabaseChangesApplied ClientChangesApplied { get; set; }

        /// <summary>
        /// Gets or Sets the conflict resolution policy from the server.
        /// </summary>
        [DataMember(Name = "crp", IsRequired = false, EmitDefaultValue = false, Order = 8)]
        public ConflictResolutionPolicy ConflictResolutionPolicy { get; set; }

        /// <summary>
        /// Gets or Sets the server's unique scope identifier.
        /// </summary>
        [DataMember(Name = "ssid", IsRequired = false, EmitDefaultValue = false, Order = 9)]
        public Guid ServerScopeId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether batch creation is still in progress (HTTP 202 scenario).
        /// When true, the client should retry after the specified <see cref="RetryAfterSeconds"/> delay.
        /// </summary>
        [DataMember(Name = "ip", IsRequired = false, EmitDefaultValue = false, Order = 10)]
        public bool InProgress { get; set; }

        /// <summary>
        /// Gets or sets the progress percentage for async batch creation (0-100).
        /// Only meaningful when <see cref="InProgress"/> is true.
        /// </summary>
        [DataMember(Name = "prg", IsRequired = false, EmitDefaultValue = false, Order = 11)]
        public int? AsyncProgress { get; set; }

        /// <summary>
        /// Gets or sets the suggested retry delay in seconds (for 202 InProgress responses).
        /// The client should wait this amount of time before retrying the request.
        /// </summary>
        [DataMember(Name = "ra", IsRequired = false, EmitDefaultValue = false, Order = 12)]
        public int? RetryAfterSeconds { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether more batch parts are being created and client should poll for additional batches.
        /// Used with progressive batch streaming.
        /// </summary>
        [DataMember(Name = "mbp", IsRequired = false, EmitDefaultValue = false, Order = 13)]
        public bool MoreBatchesPending { get; set; }

        /// <summary>
        /// Gets or sets the index of the last batch part in this response.
        /// Client sends this back to get only new batches.
        /// Used with progressive batch streaming.
        /// </summary>
        [DataMember(Name = "lbi", IsRequired = false, EmitDefaultValue = false, Order = 14)]
        public int? LastBatchIndex { get; set; }
    }

    /// <summary>
    /// HttpMessage to send an end session request to the server.
    /// </summary>
    [DataContract(Name = "endsessionreq"), Serializable]
    public class HttpMessageEndSessionRequest : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageEndSessionRequest" />
        public HttpMessageEndSessionRequest()
        {
        }

        /// <inheritdoc cref="HttpMessageEndSessionRequest" />
        public HttpMessageEndSessionRequest(SyncContext context)
            => this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <summary>
        /// Gets or Sets the SyncContext.
        /// </summary>
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets the time when a sync sessionn started.
        /// </summary>
        [DataMember(Name = "st", IsRequired = true, Order = 2)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Gets or sets the time when a sync session ended.
        /// </summary>
        [DataMember(Name = "ct", IsRequired = true, Order = 3)]
        public DateTime CompleteTime { get; set; }

        /// <summary>
        /// Gets or Sets the summary of client changes that where applied on the server.
        /// </summary>
        [DataMember(Name = "cas", IsRequired = false, Order = 4, EmitDefaultValue = false)]
        public DatabaseChangesApplied ChangesAppliedOnServer { get; set; }

        /// <summary>
        /// Gets or Sets the summary of server changes that where applied on the client.
        /// </summary>
        [DataMember(Name = "cac", IsRequired = false, Order = 5, EmitDefaultValue = false)]
        public DatabaseChangesApplied ChangesAppliedOnClient { get; set; }

        /// <summary>
        /// Gets or Sets the summary of snapshot changes that where applied on the client.
        /// </summary>
        [DataMember(Name = "scac", IsRequired = false, Order = 6, EmitDefaultValue = false)]
        public DatabaseChangesApplied SnapshotChangesAppliedOnClient { get; set; }

        /// <summary>
        /// Gets or Sets the summary of client changes to be applied on the server.
        /// </summary>
        [DataMember(Name = "ccs", IsRequired = false, Order = 7, EmitDefaultValue = false)]
        public DatabaseChangesSelected ClientChangesSelected { get; set; }

        /// <summary>
        /// Gets or Sets the summary of server changes selected to be applied on the client.
        /// </summary>
        [DataMember(Name = "scs", IsRequired = false, Order = 8, EmitDefaultValue = false)]
        public DatabaseChangesSelected ServerChangesSelected { get; set; }

        /// <summary>
        /// Gets or Sets the exception occured on client if any.
        /// </summary>
        [DataMember(Name = "exc", IsRequired = false, Order = 9, EmitDefaultValue = false)]
        public string SyncExceptionMessage { get; set; }
    }

    /// <summary>
    /// HttpMessage to get the end session response from the server.
    /// </summary>
    [DataContract(Name = "endsessionres"), Serializable]
    public class HttpMessageEndSessionResponse : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageEndSessionResponse" />
        public HttpMessageEndSessionResponse() { }

        /// <inheritdoc cref="HttpMessageEndSessionResponse" />
        public HttpMessageEndSessionResponse(SyncContext context)
            => this.SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <inheritdoc  />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }
    }

    /// <summary>
    /// Combined incremental sync request message that extends the base HttpMessageSendChangesRequest.
    /// Optimizes sync by combining BeginSession + EnsureScopes + GetOperation + SendChanges into a single request.
    /// NOTE: Only used for the FIRST batch of client changes. Multi-batch scenarios fall back to traditional flow.
    /// </summary>
    [DataContract(Name = "increq"), Serializable]
    public class HttpMessageSendChangesIncrementalRequest : HttpMessageSendChangesRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpMessageSendChangesIncrementalRequest"/> class.
        /// </summary>
        public HttpMessageSendChangesIncrementalRequest() : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HttpMessageSendChangesIncrementalRequest"/> class with the specified context and client scope info.
        /// </summary>
        /// <param name="context">The synchronization context.</param>
        /// <param name="cScopeInfoClient">The client scope information.</param>
        public HttpMessageSendChangesIncrementalRequest(SyncContext context, ScopeInfoClient cScopeInfoClient) 
            : base(context, cScopeInfoClient)
        {
        }

        /// <summary>
        /// Gets or sets the schema hash for validation to ensure client and server schema compatibility.
        /// </summary>
        [DataMember(Name = "sh", IsRequired = false, Order = 20)]
        public string SchemaHash { get; set; }

        /// <summary>
        /// Gets or sets the client schema version for compatibility checking.
        /// </summary>
        [DataMember(Name = "csv", IsRequired = false, Order = 21)]
        public string ClientSchemaVersion { get; set; }
    }
    /// <summary>
    /// Combined incremental sync response message that extends the base HttpMessageSummaryResponse.
    /// Provides additional properties specific to incremental synchronization operations including 
    /// operation type, schema validation, and server scope information.
    /// </summary>
    [DataContract(Name = "incres"), Serializable]
    public class HttpMessageSendChangesIncrementalResponse : HttpMessageSummaryResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpMessageSendChangesIncrementalResponse"/> class.
        /// </summary>
        public HttpMessageSendChangesIncrementalResponse() : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HttpMessageSendChangesIncrementalResponse"/> class with the specified context.
        /// </summary>
        /// <param name="context">The synchronization context.</param>
        /// <exception cref="ArgumentNullException">Thrown when context is null.</exception>
        public HttpMessageSendChangesIncrementalResponse(SyncContext context) : base(context)
        {
        }

        /// <summary>
        /// Gets or sets the sync operation determined by the server for incremental sync processing.
        /// </summary>
        [DataMember(Name = "op", IsRequired = false, Order = 20)]
        public SyncOperation Operation { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the client schema is valid and compatible with the server schema.
        /// </summary>
        [DataMember(Name = "sv", IsRequired = false, Order = 21)]
        public bool SchemaValid { get; set; }

        /// <summary>
        /// Gets or sets the server scope info (only sent if schema is invalid or needs to be updated).
        /// </summary>
        [DataMember(Name = "ssi", IsRequired = false, Order = 22)]
        public ScopeInfo ServerScopeInfo { get; set; }

        /// <summary>
        /// Gets or sets the server capabilities for HTTP protocol optimization.
        /// </summary>
        [DataMember(Name = "scap", IsRequired = false, Order = 23)]
        public string ServerCapabilities { get; set; }

        /// <summary>
        /// Gets or sets the server version for capability tracking.
        /// </summary>
        [DataMember(Name = "sver", IsRequired = false, Order = 24)]
        public string ServerVersion { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when capabilities were last updated.
        /// </summary>
        [DataMember(Name = "cu", IsRequired = false, Order = 25)]
        public DateTime? CapabilitiesLastUpdated { get; set; }
    }

    /// <summary>
    /// Request for reporting sync errors after session completion.
    /// </summary>
    [DataContract(Name = "errorreq"), Serializable]
    public class HttpMessageSendSyncErrorsRequest : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageSendSyncErrorsRequest" />
        public HttpMessageSendSyncErrorsRequest()
        {
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets the session identifier.
        /// </summary>
        [DataMember(Name = "sid", IsRequired = true, Order = 2)]
        public Guid SessionId { get; set; }

        /// <summary>
        /// Gets or sets the scope name.
        /// </summary>
        [DataMember(Name = "sn", IsRequired = true, Order = 3)]
        public string ScopeName { get; set; }

        /// <summary>
        /// Gets or sets the client identifier.
        /// </summary>
        [DataMember(Name = "cid", IsRequired = true, Order = 4)]
        public Guid ClientId { get; set; }

        /// <summary>
        /// Gets or sets the error timestamp.
        /// </summary>
        [DataMember(Name = "et", IsRequired = true, Order = 5)]
        public DateTime ErrorTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the serialized exception information.
        /// </summary>
        [DataMember(Name = "ex", IsRequired = false, Order = 6)]
        public SerializableExceptionInfo SyncException { get; set; }

        /// <summary>
        /// Gets or sets the error context.
        /// </summary>
        [DataMember(Name = "ctx", IsRequired = false, Order = 7)]
        public SyncErrorContext ErrorContext { get; set; }

        /// <summary>
        /// Create error request from exception.
        /// </summary>
        public static HttpMessageSendSyncErrorsRequest FromException(
            SyncContext context, Exception exception, SyncErrorContext errorContext = null)
        {
            return new HttpMessageSendSyncErrorsRequest
            {
                SyncContext = context,
                SessionId = context.SessionId,
                ScopeName = context.ScopeName,
                ClientId = context.ClientId ?? Guid.Empty,
                ErrorTimestamp = DateTime.UtcNow,
                SyncException = SerializableExceptionInfo.FromException(exception),
                ErrorContext = errorContext
            };
        }
    }

    /// <summary>
    /// Response for sync error reporting.
    /// </summary>
    [DataContract(Name = "errorres"), Serializable]
    public class HttpMessageSendSyncErrorsResponse : IScopeMessage
    {
        /// <inheritdoc cref="HttpMessageSendSyncErrorsResponse" />
        public HttpMessageSendSyncErrorsResponse()
        {
        }

        /// <inheritdoc />
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the error was received.
        /// </summary>
        [DataMember(Name = "er", IsRequired = false, Order = 2)]
        public bool ErrorReceived { get; set; }

        /// <summary>
        /// Gets or sets the server-generated error tracking ID.
        /// </summary>
        [DataMember(Name = "eid", IsRequired = false, Order = 3)]
        public string ErrorId { get; set; }

        /// <summary>
        /// Gets or sets the server timestamp.
        /// </summary>
        [DataMember(Name = "st", IsRequired = false, Order = 4)]
        public DateTime ServerTimestamp { get; set; }

        /// <summary>
        /// Gets or sets optional recommendations from server.
        /// </summary>
        [DataMember(Name = "rec", IsRequired = false, Order = 5)]
        public string[] Recommendations { get; set; }

        /// <summary>
        /// Gets or sets the server step.
        /// </summary>
        [DataMember(Name = "ss", IsRequired = true, Order = 6)]
        public HttpStep ServerStep { get; set; }
    }
}